ALTER TABLE user CHANGE COLUMN id 利用者番号 INT auto_increment;
ALTER TABLE user CHANGE COLUMN loginId 利用者ID varchar(10) NOT NULL;
ALTER TABLE user CHANGE COLUMN password パスワード varchar(255) NOT NULL;
ALTER TABLE user CHANGE COLUMN name 氏名 VARCHAR(10) NOT NULL;


ALTER TABLE question CHANGE COLUMN id 質問番号 INT auto_increment;
ALTER TABLE question CHANGE COLUMN userId 利用者番号 INT NOT NULL;
ALTER TABLE question CHANGE COLUMN question 質問内容 varchar(256) NOT NULL;
ALTER TABLE question CHANGE COLUMN date 投稿日 DATETIME NOT NULL;
ALTER TABLE question CHANGE COLUMN deleteFlg 削除フラグ TINYINT(1) NOT NULL DEFAULT 0; 


ALTER TABLE answer CHANGE COLUMN id 回答番号 BigINT auto_increment;
ALTER TABLE answer CHANGE COLUMN questionId 質問番号 INT NOT NULL;
ALTER TABLE answer CHANGE COLUMN userId 利用者番号 INT NOT NULL;
ALTER TABLE answer CHANGE COLUMN answer 回答内容 VARCHAR (256) NOT NULL;
ALTER TABLE answer CHANGE COLUMN date 投稿日 DATETIME NOT NULL;
ALTER TABLE answer CHANGE COLUMN deleteFlg 削除フラグ TINYINT(1) NOT NULL DEFAULT 0; 